default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("POSTGRESQL_ADDON_DB", "demo_rubyonrails_development") %>
  host: <%= ENV.fetch("POSTGRESQL_ADDON_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRESQL_ADDON_USER", "") %>
  password: <%= ENV.fetch("POSTGRESQL_ADDON_PASSWORD", "") %>
  port: <%= ENV.fetch("POSTGRESQL_ADDON_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_ADDON_DB", "demo_rubyonrails_test") %>

production:
  <<: *default
